builds:
  -
    binary: fabio
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - 7

archives:
  - id: bin
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Env.GOVERSION }}-{{ .Os }}_{{ .Arch }}'
    format: binary

checksum:
  name_template: '{{.ProjectName}}-{{.Version}}-{{ .Env.GOVERSION }}.sha256'

signs:
  -
    artifacts: checksum
